### ISSUE TITLE
github pages 열기

### ISSUE THREAD

**Issue by ratsgo** [ko-nlp/Korpora#104]
**개요**

패키지 개발 목적, 튜토리얼 등 안내하기 위한 github pages를 오픈한다

**Comment by ratsgo** [comment]
**운영 브랜치**

- `pages`라는 브랜치에서 페이지를 운영
- 이 브랜치는 페이지 운영 용도로만 사용 (패키지 관련 코드는 없음)

**Comment by ratsgo** [comment]
**페이지 운영 및 관리 방법 안내**

- https://rundocs.io

**Comment by ratsgo** [comment]
**페이지 작성 예시**

- https://github.com/rundocs/rundocs.io/tree/master/docs

**Comment by ratsgo** [comment]
**로컬 테스트**

```bash
gem install jekyll bundler

bundle install

JEKYLL_GITHUB_TOKEN=blank PAGES_API_URL=http://0.0.0.0 bundle exec jekyll server --livereload
```

**Comment by ratsgo** [comment]
**note, tip, warning, danger**

- 다음과 같이 작성하면 아래 같이 노출

<img width="110" alt="스크린샷 2020-10-05 오후 3 08 29" src="https://user-images.githubusercontent.com/26211652/95045309-a72aa280-071c-11eb-94e5-5bf42e296af4.png">

<img width="502" alt="스크린샷 2020-10-05 오후 3 09 02" src="https://user-images.githubusercontent.com/26211652/95045328-b578be80-071c-11eb-89ca-24d6ed2e5c73.png">

**Comment by lovit** [comment]
@ratsgo @warnikchow @hank110 님의 수고로 github page 에 한/영의 말뭉치 소개가 완료되었습니다. introduction, contribution 번역 잔업이 남았지만, 이는 #139 에 기술되어 있으므로 이 이슈를 닫습니다.
