### ISSUE TITLE
README 의 Corpus list 에 누락된 말뭉치가 있습니다.

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#129]
- korean_parallel_koen_news 가 corpus list 에서 누락되었습니다.
- 그 외의 실수를 방지하기 위하여 말뭉치 고정 후 README 의 corpus list 확인이 필요합니다.

**Comment by ratsgo** [comment]
확인 결과 0.2.0에서 제공하는 말뭉치를 모두 기재하였습니다.
#148 이슈에서 dev 브랜치에 머지할 README.md를 작성하고 있으므로 이 이슈는 클로즈합니다.
