### ISSUE TITLE
Typo: Open Substitles

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#144]
`Korpora.loader.py` 및 README 에 등록된 `open substitles`에 오타가 있습니다. substitles -> subtitles 로 수정해야 합니다.

**Comment by hank110** [comment]
markdown file 명 내 해당 typo는 pages-en-subtitles 에 수정해놨습니다.

**Comment by lovit** [comment]
> markdown file 명 내 해당 typo는 pages-en-subtitles 에 수정해놨습니다.

@hank110 넵 감사합니다 PR 주시면 확인하겠습니다

**Comment by lovit** [comment]
- #152 에서 `open_substitles` 라는 이름으로 `Korpora.load` 사용법이 올라갔습니다. 추가 수정이 필요합니다.
- [`pages`](https://github.com/ko-nlp/Korpora/blob/pages/ko-docs/corpuslist/open_substitles.md) 의 한글 문서에도 이 내용이 여전히 수정되지 않았습니다. 추가 수정이 필요합니다. @lovit

**Comment by lovit** [comment]
Resolved
