### ISSUE TITLE
0.2.0 버전 README 수정 반영

### ISSUE THREAD

**Issue by ratsgo** [ko-nlp/Korpora#148]
**개요**

0.2.0 README에 추가 기능과 pages, 말뭉치 설명을 반영한다

**Comment by ratsgo** [comment]
**README 반영 내용**

- 코포라 패키지 소개
- Documentation : https://ko-nlp.github.io/Korpora 안내
- 퀵 투어
  - 패키지 설치
  - 코퍼스 리스트 확인
  - 콘솔에서 다운로드하기
  - 콘솔에서 읽어들이기
  - CLI로 다운로드하기
  - CLI로 LM 데이터 처리하기
- 라이센스 안내

**Comment by ratsgo** [comment]
현재 dev, master README에는 모든 말뭉치 예제들이 있어서 다소 긴 느낌을 주는데요.
저희가 https://ko-nlp.github.io/Korpora 페이지를 별도로 운영하고 이 페이지에서 말뭉치별로 사용 방법을 상세하게 안내하고 있으니
README에는 퀵 투어 가이드 정도로만 간단히 설명하고 자세한건 페이지를 보라고 안내하는건 어떨까요?
@lovit @warnikchow @jaewonlee-728

**Comment by ratsgo** [comment]
README를 아래처럼 커밋해 두었습니다.
한번 살펴보고 의견 주셔요!

**Comment by lovit** [comment]
korpora github io 로의 링크가 있지만, 한 말뭉치에 대한 사용법을 확인하기 위해서는 직접 아래의 `korpora github io 링크를 누른` 뒤 > `말뭉치리스트를 펼치고` > `해당 말뭉치를 클릭`하는 세 단계의 사용자 작업이 필요합니다. 하여 각 말뭉치별로 korpora github io 의 상세 페이지에 링크를 넣어두면 어떨까요?

**Comment by lovit** [comment]
사용법을 거의 통일해두었기 때문에 하나의 말뭉치에 대해서만 대표적인 사용법을 README 에도 적으면 어떨까요? `NSMC` 사용법만 대표로 적어두는것은 어떤가요?

**Comment by lovit** [comment]
> korpora github io 로의 링크가 있지만, 한 말뭉치에 대한 사용법을 확인하기 위해서는 직접 아래의 `korpora github io 링크를 누른` 뒤 > `말뭉치리스트를 펼치고` > `해당 말뭉치를 클릭`하는 세 단계의 사용자 작업이 필요합니다. 하여 각 말뭉치별로 korpora github io 의 상세 페이지에 링크를 넣어두면 어떨까요?

이 내용은 위 커밋에 반영하였습니다.

**Comment by ratsgo** [comment]
현재 readme#148 브랜치에 있는 README.md가 잠정적인 확정판처럼 느껴지는데요.
한국어 설명으로 돼 있는 부분을 그대로 따서 아랫부분에 영어 버전으로 번역해 넣으면 어떨까요? 

**As is**
```
# Korpora: Korean Corpora Archives

최근 자연어 처리에 관심이 높아지면서 정부와 기업은 물론 뜻있는 개인에 이르기까지 데이터를 무료로 공개하는 추세입니다. 
...
## License
...
- 한편 말뭉치의 라이센스는 말뭉치별로 별도 적용됩니다. 자신이 사용할 말뭉치의 라이센스가 어떤 내용인지 활용 전에 반드시 확인하세요!
```

**To be**
```
# Korpora: Korean Corpora Archives

최근 자연어 처리에 관심이 높아지면서 정부와 기업은 물론 뜻있는 개인에 이르기까지 데이터를 무료로 공개하는 추세입니다. 
...
## License
...
- 한편 말뭉치의 라이센스는 말뭉치별로 별도 적용됩니다. 자신이 사용할 말뭉치의 라이센스가 어떤 내용인지 활용 전에 반드시 확인하세요!

# Korpora: Korean Corpora Archives

Recently, governments, businesses, and individuals are releasing data for free.
...
## License
...
- Please check the license of the corpus!
```

@warnikchow @jaewonlee-728 

혹은 더 좋은 방법이 있다면 제안해주셔도 됩니다.

**Comment by ratsgo** [comment]
**라이센스 정보 보완**

- 패키지를 단순 이용하는 사람에게 '추가제한금지' 내용을 부과하는 것은 다소 과하다는 의견제기
- 라이센스 정보를 다음과 같이 수정

**as-is**
```
- 이용자는 다음의 의무가 있습니다. 아래 의무를 지키는 한 위의 권리가 유효합니다.
  - 저작자표시 : Korpora를 이용했다는 정보를 표시해야 합니다. 
  - 추가제한금지 : 이용자는 Korpora를 활용한 저작물에 CC-BY보다 엄격한 라이센스를 부가할 수 없습니다.
```

**to-be**
```
- 이용자는 다음의 의무가 있습니다. 아래 의무를 지키는 한 위의 권리가 유효합니다.
  - 저작자표시 : Korpora를 이용했다는 정보를 표시해야 합니다.
  - 추가제한금지 : 이용자는 Korpora를 활용한 2차 저작물에 CC-BY보다 엄격한 라이센스를 부가할 수 없습니다.
  - 예컨대 Korpora를 내려 받아 단순히 사용하기만 했다면 '저작자표시'만 지키면 됩니다. Korpora를 활용해 모델이나 문서 등을 만들고 이를 배포할 경우 '저작자표시'뿐 아니라 '추가제한금지' 의무도 지켜야 합니다.
```

**Comment by lovit** [comment]
> **라이센스 정보 보완**
> 
> * 패키지를 단순 이용하는 사람에게 '추가제한금지' 내용을 부과하는 것은 다소 과하다는 의견제기
> * 라이센스 정보를 다음과 같이 수정
> 
> **as-is**
> 
> ```
> - 이용자는 다음의 의무가 있습니다. 아래 의무를 지키는 한 위의 권리가 유효합니다.
>   - 저작자표시 : Korpora를 이용했다는 정보를 표시해야 합니다. 
>   - 추가제한금지 : 이용자는 Korpora를 활용한 저작물에 CC-BY보다 엄격한 라이센스를 부가할 수 없습니다.
> ```
> 
> **to-be**
> 
> ```
> - 이용자는 다음의 의무가 있습니다. 아래 의무를 지키는 한 위의 권리가 유효합니다.
>   - 저작자표시 : Korpora를 이용했다는 정보를 표시해야 합니다.
>   - 추가제한금지 : 이용자는 Korpora를 활용한 2차 저작물에 CC-BY보다 엄격한 라이센스를 부가할 수 없습니다.
>   - 예컨대 Korpora를 내려 받아 단순히 사용하기만 했다면 '저작자표시'만 지키면 됩니다. Korpora를 활용해 모델이나 문서 등 2차적 저작물을 만들고 이를 배포할 경우 '저작자표시'뿐 아니라 '추가제한금지' 의무도 지켜야 합니다.
> ```

이 내용 반영되었음을 확인하였습니다.

**Comment by lovit** [comment]
> 현재 readme#148 브랜치에 있는 README.md가 잠정적인 확정판처럼 느껴지는데요.
> 한국어 설명으로 돼 있는 부분을 그대로 따서 아랫부분에 영어 버전으로 번역해 넣으면 어떨까요?
> 
> **As is**
> 
> ```
> # Korpora: Korean Corpora Archives
> 
> 최근 자연어 처리에 관심이 높아지면서 정부와 기업은 물론 뜻있는 개인에 이르기까지 데이터를 무료로 공개하는 추세입니다. 
> ...
> ## License
> ...
> - 한편 말뭉치의 라이센스는 말뭉치별로 별도 적용됩니다. 자신이 사용할 말뭉치의 라이센스가 어떤 내용인지 활용 전에 반드시 확인하세요!
> ```
> 
> **To be**
> 
> ```
> # Korpora: Korean Corpora Archives
> 
> 최근 자연어 처리에 관심이 높아지면서 정부와 기업은 물론 뜻있는 개인에 이르기까지 데이터를 무료로 공개하는 추세입니다. 
> ...
> ## License
> ...
> - 한편 말뭉치의 라이센스는 말뭉치별로 별도 적용됩니다. 자신이 사용할 말뭉치의 라이센스가 어떤 내용인지 활용 전에 반드시 확인하세요!
> 
> # Korpora: Korean Corpora Archives
> 
> Recently, governments, businesses, and individuals are releasing data for free.
> ...
> ## License
> ...
> - Please check the license of the corpus!
> ```

이 내용 @hank110 께 부탁해도 될까요? 일정 가능하신가요?

**Comment by hank110** [comment]
@lovit 위 commit으로 readme#148 브랜치 내 README.md 영문화 작업 완료했습니다.

**Comment by lovit** [comment]
내용이 모두 반영되어 이슈를 닫습니다.
