### ISSUE TITLE
Metric 기능 제공

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#15]
- huggingface.nlp 에서 metric 기능을 제공합니다.
- sentence classification tasks / sentence pair classification tasks / sequential labeling (NER, POS, SRL) tasks 등에 이용할 수 있는 evaluation metric 을 제공하는 것이 어떨까요?
- 아래는 현재 huggingface.nlp 에서 제공하는 metrics 입니다. 이용할 수 있는 것은 래핑해서 이용하고, 기본적인 evaluation 척도들은 (including precision / recall / f1 score report) 추가로 제공해주면 좋을 것 같아요
  - scikit-learn 의 classification report 기능도 매우 좋다고 생각해요.
  - 하지만 evaluation 을 위하여 nlp / scikit-learn 에 package dependency 를 건다는 점이 부담스럽긴 합니다.

![image](https://user-images.githubusercontent.com/3401574/91643264-9bd4bf00-ea6c-11ea-8e08-f55476e2ed9b.png)

**Comment by ratsgo** [comment]
Korpora가 다양한 데이터 셋에 대한 다운로드, 전처리 등을 지원하는 패키지이니
metric 기능을 제공하는 것 역시 당연한 수순이라고 생각합니다.
외부 패키지 의존성 없이 가볍게 만들 수 있다면 
Korpora에서 metric 함수들을 지원하면 좋을 것 같습니다.

**Comment by lovit** [comment]
의견 감사해요 이 부분도 같이 고민/작업해 봐요

나의 iPhone에서 보냄

**Comment by lovit** [comment]
@ratsgo evaluation 기능은 `Korpora` package 에 의존성이 없도록 작성할 예정이기 때문에 `dev` 가 아닌 `evaluation` branch 에서 작업하도록 하겠습니다. 하지만 README 등의 변화를 고려하여 [현재의  `dev`](https://github.com/ko-nlp/Korpora/commit/cfc6b5aa5ce6c3d14f71ff6da7d654d958984879) 에 base 를 두겠습니다.

**Comment by lovit** [comment]
`Korpora-metrics` 에서 작업을 이어가겠습니다. 관련 이슈도 해당 레포지토리에서 논의할 예정이라 이 이슈를 close 합니다.
