### ISSUE TITLE
모두의 말뭉치 신청 현황

### ISSUE THREAD

**Issue by ratsgo** [ko-nlp/Korpora#3]
**개요**

[국립국어원 모두의 말뭉치](https://corpus.korean.go.kr) 신청 현황을 정리한다

**Comment by lovit** [comment]
주로 적업을 많이 하는 @lovit @ratsgo 는 Korpora 개발용으로 모두의 말뭉치 사용 권한을 완료하였습니다.

**Comment by lovit** [comment]
이 이슈는 완료되었기에 닫겠습니다.
