### ISSUE TITLE
Show license and description when loading or fetching corpus

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#52]
@ratsgo @hungry-wook 

말뭉치를 공개해주신 분들의 노력을 알리는 것은 지속적으로 해야 하는 일이며, 말뭉치를 사용할 때 라이센스를 확인하는 작업은 정말로 중요하다고 생각합니다. 하여 fetch 혹은 Korpus class instance 를 만들 때 라이센스와 reference 가 포함된 description 을 print 하면 어떨까요?
그리고 이 기능은 `0.1.0` 부터 포함되어야 한다고 생각합니다.
자연어처리 커뮤니티 발전을 위해서 코퍼스 작업을 해주신 분들의 노력을 알려주는 것도 Korpora project 의 목표 중 하나라고 생각하며, 처음 릴리즈 할 때 이러한 의도가 패키지 내에서 보여졌으면 해서입니다.

**Comment by hungry-wook** [comment]
동의합니다. 덧붙여, Readme에도 드러나게 정리하면 좋을것 같습니다.

**Comment by ratsgo** [comment]
저도 전적으로 동의합니다! 해당 정보 제공은 데이터를 공개해주신 분들에 대한 예의인 것 같습니다.
