### ISSUE TITLE
CORPUS_INFORMATION 의 item 의 indentation 수정

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#71]
`korpora_xxx.py` 의 `xxx_CORPUS_INFORMATION` 내의 아이템들이 4 칸 들여쓰기가 아닌 경우들이 있습니다. 전체 파일들에 대하여 indentation 을 수정합니다.

**Comment by ratsgo** [comment]
dev 및 master 브랜치에 반영되었으므로 이슈 클로즈합니다
