### ISSUE TITLE
파일 별 다운로드

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#8]
- 여러 개의 파일로 구성된 코퍼스의 경우, 파일이 하나라도 없으면 전체를 다운로드 받습니다.
- 파일별로 재 다운로드 받도록 fetch 기능을 수정하면 어떨까요?

**Comment by lovit** [comment]
- 용량 확인 후 알려진 용량과 다를 경우 파일 오버라이딩

**Comment by lovit** [comment]
차후에는 아래와 같은 구조로 corpus urls 를 가지고 있어야 하지만,

```
CORPUS_URLS = [
  {'url': 'url', 'size': 1234, 'destination': 'path/to/destination'},
  {'url': 'url', 'size': 1234, 'destination': 'path/to/destination'},
 ...
]
```

용량 체크하는 기능을 구현하기 전에는 아래와 같은 구조로 corpus urls 를 가지고 있어도 좋습니다. 아래의 정보가 #39 이슈의 결과물로 있으면 어떨까요?

```
CORPUS_URLS = [
  {'url': 'url', 'destination': 'path/to/destination'},
  {'url': 'url', 'destination': 'path/to/destination'},
 ...
]
```

**Comment by ratsgo** [comment]
> 차후에는 아래와 같은 구조로 corpus urls 를 가지고 있어야 하지만,
> 
> ```
> CORPUS_URLS = [
>   {'url': 'url', 'size': 1234, 'destination': 'path/to/destination'},
>   {'url': 'url', 'size': 1234, 'destination': 'path/to/destination'},
>  ...
> ]
> ```
> 
> 용량 체크하는 기능을 구현하기 전에는 아래와 같은 구조로 corpus urls 를 가지고 있어도 좋습니다. 아래의 정보가 #39 이슈의 결과물로 있으면 어떨까요?
> 
> ```
> CORPUS_URLS = [
>   {'url': 'url', 'destination': 'path/to/destination'},
>   {'url': 'url', 'destination': 'path/to/destination'},
>  ...
> ]
> ```

네 동의합니다. 아울러 이번 이슈는 https://github.com/ko-nlp/Korpora/issues/39 와 긴밀한 연관이 있으므로 이 이슈와 병합해 단일 PR로 진행하겠습니다.
