### ISSUE TITLE
데이터 관리 방법에 대한 질문

### ISSUE THREAD

**Issue by shuuki4** [ko-nlp/Korpora#82]
`KoreanPetitions` 데이터를 예시로 들어보면,

현재 코퍼스의 instance하나를 `KoreanPetition`, 데이터를 `KoreanPetitionsData` 클래스로 구현하고 있고 `KoreanPetitionsData`의 `__getitem__`에서 on-the-fly로 `KoreanPetition` dataclass를 만드는 식으로 관리되고 있는 것 같습니다.

`KorpusData`가 데이터를 `List[KoreanPetition]` (or `List[CorpusSpecificSingleData]`) 형태로 들고 있으면 굳이 코퍼스마다 `*Data` 클래스를 새로 정의해줄 필요가 없어 관리 차원에서 조금 더 유용할것 같은데요! 혹시 현재 구현처럼 관리되고 있는 특별한 이유가 있을까요?

**Comment by lovit** [comment]
아래처럼 KorpusData 를 상속하는 class A 의 class name 을 확인했을 때 해당 데이터가 어떤 코퍼스의 데이터인지 확인할 수 있도록 만들고 싶었습니다.

```python
class A(KorpusData):
    # ...
```

https://github.com/ko-nlp/Korpora/blob/master/Korpora/korpora.py#L34 이 기능에서 해당 정보가 표현되게 하려고 `*Data` 로 클래스를 정의하고 있습니다.

**Comment by lovit** [comment]
아직도 어떻게 해야 이후 코퍼스를 편리하게 확장하면서도 정보를 최대한 잘 표현할 수 있을지 고민이에요. 다양한 아이디어 혹은 질문들 남겨주세요~ 고마워요 !! @shuuki4

**Comment by lovit** [comment]
다시 생각해보니 `KorpusData` 클래스의 init 에 `name` 을 받도록 만들고, `__str__` 에서 `name` 을 출력하는 형식으로 바꾸면 @shuuki4 님의 커멘트처럼 class 를 재활용 할 수 있겠네요. 이 점 고려하여 패키지의 클래스 구조 다시 고민해보겠습니다. 감사해요~!

**Comment by lovit** [comment]
이 이슈를 해결중입니다. 이 이슈와 함께 `Korpus.__str__` 과 `KorpusData.__str__` 도 수정중입니다. 현재의 예시는 다음과 같습니다.


## NSMCKorpus

`str(nsmc)`
```
NSMCKorpus
    Author : e9t@github
    Repository : https://github.com/e9t/nsmc
    References : www.lucypark.kr/docs/2015-pyconkr/#39

    Naver sentiment movie corpus v1.0
    This is a movie review dataset in the Korean language.
    Reviews were scraped from Naver Movies.

    The dataset construction is based on the method noted in
    [Large movie review dataset][^1] from Maas et al., 2011.

    [^1]: http://ai.stanford.edu/~amaas/data/sentiment/

Attributes
----------
NSMC.train
  - NSMC.train.texts (list[str]) : size=150000
  - NSMC.train.labels (list[int]) : size=150000
NSMC.test
  - NSMC.test.texts (list[str]) : size=50000
  - NSMC.test.labels (list[int]) : size=50000
```

`str(nsmc.train)`
```
NSMC.train
  - NSMC.train.texts (list[str]) : size=150000
  - NSMC.train.labels (list[int]) : size=150000
```

## QuestionPairKorpus

`str(korpus)`
```
QuestionPairKorpus
    Author : songys@github
    Repository : https://github.com/songys/Question_pair
    References :

    질문쌍(Paired Question v.2)
    짝 지어진 두 개의 질문이 같은 질문인지 다른 질문인지 핸드 레이블을 달아둔 데이터
    사랑, 이별, 또는 일상과 같은 주제로 도메인 특정적이지 않음

Attributes
----------
QuestionPair.train
  - QuestionPair.train.texts (list[str]) : size=6888
  - QuestionPair.train.pairs (list[str]) : size=6888
  - QuestionPair.train.labels (list[str]) : size=6888
QuestionPair.test
  - QuestionPair.test.texts (list[str]) : size=688
  - QuestionPair.test.pairs (list[str]) : size=688
  - QuestionPair.test.labels (list[str]) : size=688
```

`str(korpus.train)`
```
QuestionPair.train
  - QuestionPair.train.texts (list[str]) : size=6888
  - QuestionPair.train.pairs (list[str]) : size=6888
  - QuestionPair.train.labels (list[str]) : size=6888
```
