### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by hungry-wook** [ko-nlp/Korpora#89]
사용 예제에서 import하는 모듈명에 `Korpus`가 누락되었습니다.
`KoreanHateSpeech` -> `KoreanHateSpeechKorpus`
`KoreanPetitions` -> `KoreanPetitionsKorpus`
`KorNLI` -> `KorNLIKorpus`
`KorSTS` -> `KorSTSKorpus`
`NSMC` -> `NSMCKorpus`

**Comment by lovit** [comment]
@ratsgo 이 부분은 hotfix 로 고쳐야 할듯합니다. REAMDE 인만큼 master 에 곧바로 반영하겠습니다.

**Comment by lovit** [comment]
@hungry-wook 커멘트 감사합니다. 클래스 내 이름 통일하는 과정에서 리드미에 누락이 있었네요. 곧바로 반영하겠습니다.

**Comment by lovit** [comment]
@hungry-wook 해당 이슈 반영하여 README 를 업데이트 하였습니다.
