### ISSUE TITLE
네이버 x 창원대 NER

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#9]
- #6 링크 중 NER competitions 의 데이터
- https://github.com/naver/nlp-challenge/tree/master/missions/ner
- data loader 제공되어 있으며, 아래와 같은 형식의 데이터
- 이 데이터를 통하여 word-level tagging 데이터 형식에 대한 합의를 할 수 있을 것으로 기대

```
1	비토리오	PER_B
2	양일	DAT_B
3	만에	-
4	영사관	ORG_B
5	감호	CVL_B
6	용퇴,	-
7	항룡	-
8	압력설	-
9	의심만	-
10	가율	-

1	이	-
2	음경동맥의	-
3	직경이	-
4	8	NUM_B
5	19mm입니다	NUM_B
6	.	-

1	9세이브로	NUM_B
2	구완	-
3	30위인	NUM_B
4	LG	ORG_B
```

**Comment by ratsgo** [comment]
> @ratsgo
> 
> 아래와 같이 세 개의 attributes 를 지니는 KorpusData 로 만들면 어떨까요?
> 
> ```python
> class NaverNERCorpusData(KorpusData):
>     words : List[List[str]]
>     tags : List[List[str]]
> 
> naver_ner = NaverNERCorpusData()
> naver_ner.texts # list of str
> naver_ner.words # list of list of str
> naver_ner.tags # list of list of str
> ```

좋은 생각입니다! 동의합니다.

**Comment by lovit** [comment]
> > @ratsgo
> > 아래와 같이 세 개의 attributes 를 지니는 KorpusData 로 만들면 어떨까요?
> > ```python
> > class NaverNERCorpusData(KorpusData):
> >     words : List[List[str]]
> >     tags : List[List[str]]
> > 
> > naver_ner = NaverNERCorpusData()
> > naver_ner.texts # list of str
> > naver_ner.words # list of list of str
> > naver_ner.tags # list of list of str
> > ```
> 
> 좋은 생각입니다! 동의합니다.

네 이대로 추진하겠습니다.
