### ISSUE TITLE
[Corpus] Fix namuwikitext typo

### ISSUE THREAD

**Issue by sackoh** [ko-nlp/Korpora#98]
안녕하세요
먼저, 이렇게 훌륭한 프로젝트를 시작해주신 것에 대해 감사의 말씀드립니다.

나무위키 데이터를 fetch 하던 중에 namuwiki 경로에서 데이터를 직접 불려오려고 했는데
not found 에러가 발생해서 보니 디렉토리명이 `namiwiki` 로 되어있었네요. [link](https://github.com/ko-nlp/Korpora/blob/master/Korpora/korpus_namuwiki.py)

의도하신 것인지 모르겠으나 혹시나 `namuwiki`를 잘못 작성하신가하여 올립니다.
에러와 관련된 이슈는 아니라 송구합니다.

다시 한번 감사드립니다.

```python
NAMUWIKI_FETCH_INFORMATION = [
    {
        'url': 'https://github.com/lovit/namuwikitext/releases/download/v0.1/namuwikitext_20200302.v0.1.train.zip',
        'destination': 'namiwiki/namuwikitext_20200302.train.zip',
        'method': 'download & unzip'
    },
    {
        'url': 'https://github.com/lovit/namuwikitext/releases/download/v0.1/namuwikitext_20200302.v0.1.test.zip',
        'destination': 'namiwiki/namuwikitext_20200302.test.zip',
        'method': 'download & unzip'
    },
    {
        'url': 'https://github.com/lovit/namuwikitext/releases/download/v0.1/namuwikitext_20200302.v0.1.dev.zip',
        'destination': 'namiwiki/namuwikitext_20200302.dev.zip',
        'method': 'download & unzip'
    }
]
```

```python
                    dirname = os.path.abspath(f'{root_dir}/namiwiki')
                    self.train = f'Namuwikitext corpus is downloaded. Open local directory {dirname}'
                    print('Continue to load `dev` and `test`')
```

**Comment by lovit** [comment]
이 문제는 지적해주신 내용이 맞습니다 저희가 작업하면서 namuwiki 와 namuwikitext 를 혼용하며 사용하였네요 빠른 시일내에 고치겠습니다. 모든 커멘트는 저희에게 정말 소중합니다. 기여를 해주셔서 감사합니다.!

**Comment by lovit** [comment]
수정하면서 오타도 함께 수정해 둘게요

**Comment by sackoh** [comment]
네, 감사합니다!
기회가 된다면 다른 부분에서도 기여드릴 수 있도록 하겠습니다.

**Comment by lovit** [comment]
@ratsgo 저희가 large size data 라 수동으로 테스트 하는 부분에서 typo 에 의한 오류가 발견되었네요. 사용하시는 분들이 원활히 해당 말뭉치를 이용할 수 있도록 dev 가 아닌 master 로 수정한 뒤, 0.1.x 로, 0.2 이전에 우선배포하면 어떨까요?

**Comment by ratsgo** [comment]
@lovit 네 해당 typo는 다음 버전 정식 릴리즈 전에 먼저 고쳐지는게 좋을 것 같습니다! 마스터에 바로 반영하죠

@sackoh 님 오류 제보해 주셔서 진심으로 감사드립니다!

**Comment by lovit** [comment]
해당 이슈 수정하여 0.1.1 로 배포하였습니다. pip install 로도 재배포 된 버전을 설치하실 수 있습니다.
